# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Cody Nguyen
email: cody.nguyen94@gmail.com
description: >-
  A blog.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
permalink: /blog/:slug
timezone: America/New_York
future: false

# Build settings
remote_theme: pages-themes/dinky@v0.2.0
plugins:
  - jekyll-remote-theme 
  - jekyll-feed
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from

markdown: kramdown

compress_html:
  clippings: all
  comments: [""]
  endings: [html, head, body, li, dt, dd, rt, rp, optgroup, option, colgroup, caption, thead, tbody, tfoot, tr, td, th]
  profile: false
  blanklines: false
  ignore:
    envs: []

# sass:
#   sass_dir: css
#   style:    compressed

collections:
  my_tags:
    output: true
    permalink: /tagged/:slug/
defaults:
  -
    scope:
      path: ""
      type: my_tags
    values:
      layout: tagged

exclude:
- README.md
- LICENSE.md
- vendor

Blog: /blog

# Add general links to site pages here
links:
  Resume: /assets/resume.pdf
  
# Add links for more focus here
special_links:
  "Search": https://duckduckgo.com
